baseURL = "https://sk2.jsiu.dev"
theme   = "sk2"
title   = "SK2"

[Params]
mainSections = "post"
startdate    = "2012-12-02"
subtitle     = "A Hugo Theme"
summary      = true
toc          = true

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1