name = "sk2"
license = "MIT"
licenselink = "https://github.com/J-Siu/hugo-theme-sk2/blob/master/LICENSE"
description = "Fully functional basic Hugo theme, no css, no javascript."
homepage = "https://sk2.jsiu.dev/"
tags = ["blog"]
features = []
min_version = "0.65.0"

[author]
  name = "John Siu"
  homepage = "https://github.com/J-Siu"