demosite="https://sk2.jsiu.dev"
description = "Demo/Tutorial Hugo theme. Fully functional with minimum css, no javascript."
features    = []
homepage    = "https://github.com/J-Siu/hugo-theme-sk2"
license     = "MIT"
licenselink = "https://github.com/J-Siu/hugo-theme-sk2/blob/master/LICENSE"
name        = "SK2"
tags        = ["blog", "clean", "minimal", "personal", "simple"]

[author]
homepage = "https://johnsiu.com/"
name     = "John Siu"
